repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: local
    hooks:
      - id: black
        name: Black Python code formatting
        entry: bash -c 'black app/; git add -u' --
        language: python
        files: \.py$
        types: [python]
      - id: isort
        name: Sorting import statements
        entry: bash -c 'isort app/; git add -u' --
        language: python
        args: ["--profile", "black", "--filter-files", "--skip-gitignore"]
        files: \.py$
      - id: flake8
        name: Flake8 Python style check
        entry: bash -c 'flake8 app/' --
        language: python
        files: \.py$

